const fs=require('fs');
const vm=require('vm');
const path=require('path');
const file=path.join(__dirname,'..','docs','agewell-city-core.js');
const source=fs.readFileSync(file,'utf8');
const context={window:{},console,Date};
vm.createContext(context);
vm.runInContext(source,context,{filename:file});
const core=context.window.AgeWellCityCore;
function assert(cond,msg){if(!cond)throw new Error(msg);}
const independent=core.runScenario('independent',{run_id:'test-independent'});
assert(independent.status==='SUPPORTED_STABLE','independent scenario should reach SUPPORTED_STABLE');
assert(independent.resident.consent==='ACTIVE','consent should remain active');
assert(independent.counters.handoffs>0,'independent scenario should include agent handoffs');
assert(independent.counters.bounded_actions>0,'independent scenario should include bounded support actions');
const assisted=core.runScenario('assisted',{run_id:'test-assisted'});
assert(assisted.status==='COORDINATED','assisted scenario should reach COORDINATED');
const heat=core.runScenario('heat',{run_id:'test-heat'});
assert(heat.status==='COMMUNITY_STABLE','heat scenario should reach COMMUNITY_STABLE');
const denied=core.requestProtectedAction(independent,'agewell.medication.change','test');
assert(denied.status==='HUMAN_REVIEW','protected action should force HUMAN_REVIEW');
assert(denied.blockers.some(b=>b.code==='PROTECTED_AUTHORITY'),'protected action should create PROTECTED_AUTHORITY blocker');
assert(denied.events.some(e=>e.type==='tool.denied'),'protected action should record tool.denied');
const stale=core.injectSecondaryFault(independent);
assert(stale.status==='HUMAN_REVIEW','stale evidence should force HUMAN_REVIEW');
assert(stale.blockers.some(b=>b.code==='STALE_HOME_EVIDENCE'),'stale home evidence blocker should be present');
const self=core.runSelfTest();
assert(self.ok===true,'runtime self test should pass');
assert(core.packageRun(independent).events.length===independent.events.length,'exported package should preserve events');
console.log(`AGEWELL CITY runtime tests passed: ${self.passed}/${self.total} self tests`);